#:schema https://raw.githubusercontent.com/astral-sh/ruff/main/ruff.schema.json

select = [
    "ALL",

    # Nursery (Not enabled by ALL selector):
    "E111", "E112", "E113", "E114", "E115", "E116", "E117",
    "E201", "E202", "E203",
    "E211",
    "E221", "E222", "E223", "E224", "E225", "E226", "E227", "E228",
    "E231",
    "E241", "E242",
    "E251", "E252",
    "E261", "E262", "E265", "E266",
    "E271", "E272", "E273", "E274", "E275",

    "RUF017",

    "PLC1901", "PLW1641", "PLW3201"
]

ignore = [
    "D1",       # undocumented-*
    "COM812",   # missing-trailing-comma
    "D203",     # one-blank-line-before-class (Incompatible with D211 no-blank-line-before-class)
    "D213",     # multi-line-summary-second-line (Incompatible with D212 multi-line-summary-first-line)
    "FBT",      # flake8-boolean-trap
    "ERA001",   # commented-out-code
    "TRY300",   # try-consider-else
    "TD",       # flake8-todos
    "FIX",      # flake8-fixme


    "ANN001",   # missing-type-function-argument
    "ANN002",   # missing-type-args
    "ANN003",   # missing-type-kwargs
    "ANN101",   # missing-type-self
    "ANN201",   # missing-return-type-undocumented-public-function

    "INP001",   # implicit-namespace-package

    "S602",     # subprocess-popen-with-shell-equals-true
    "S603",     # subprocess-without-shell-equals-true

    "G004",     # logging-f-string

    "PLR2004",  # magic-value-comparison
]

unfixable = ["B", "UP", "C4", "SIM"]

format = "grouped"

pylint.max-args = 10

pylint.max-returns = 10

line-length = 145

flake8-quotes.inline-quotes = "double"

target-version = "py38"

extend-exclude = ["unit_tests", "test"]
